import { Html, Head, Main, NextScript } from 'next/document';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <meta name="keywords" content="slot, gambling, online casino" />
        <meta name="author" content="Fipbet Team" />
        <meta property="og:title" content="Fipbet Slot Gacor" />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.fipbet.com" />
        <meta property="og:image" content="https://www.fipbet.com/images/og-image.jpg" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "Fipbet Slot Gacor",
              "url": "https://www.fipbet.com",
              "sameAs": [
                "https://www.facebook.com/fipbet",
                "https://www.twitter.com/fipbet",
                "https://www.instagram.com/fipbet"
              ],
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://www.fipbet.com/search?query={search_term_string}",
                "query-input": "required name=search_term_string"
              }
            }),
          }}
        />
      </Head>
      <body className={inter.className}>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
